project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: false

website:
  title: "ASM 2022 Workshop - GitHub"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/njlyon0/asm-2022_github-workshop
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: "Workflows"
        href: workflows.qmd
      - text: "GitHub"
        href: github.qmd
      - text: "RStudio"
        href: rstudio.qmd
      - text: "Appendix"
        href: setup.qmd
    right:
      - text: "Content Creators"
        menu:
          - text: "Angel Chen"
            href: https://angelchen7.github.io/
          - text: "Nick Lyon"
            href: https://njlyon0.github.io/      
      - icon: github
        href: https://github.com/njlyon0/asm-2022_github-workshop
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary
  margin-footer:
    <img src="images/lter-logo.png" width="40%"/>
    <img src="images/nceas-logo.png" width="40%"/>

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    